# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(help_text='Maximo 50 caracteres', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Marcass',
            },
        ),
        migrations.AlterModelOptions(
            name='socios',
            options={'verbose_name_plural': 'Socioss'},
        ),
    ]
