# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20170109_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Bateriass',
            },
        ),
    ]
