# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_rines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aceites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Aceitess',
            },
        ),
        migrations.CreateModel(
            name='TipoAceite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'TipoAceitess',
            },
        ),
        migrations.AddField(
            model_name='aceites',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TipoAceite'),
        ),
    ]
