# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20170112_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Filtross',
            },
        ),
        migrations.CreateModel(
            name='TipoFiltro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'TipoFiltross',
            },
        ),
        migrations.AddField(
            model_name='filtros',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TipoFiltro'),
        ),
    ]
