# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-16 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20170113_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=12, unique=True)),
                ('descripcion', models.CharField(help_text='Maximo 100 caracteres', max_length=100)),
                ('nombre', models.TextField(help_text='Maximo 100 caracteres', max_length=100)),
                ('direccion', models.TextField(help_text='Maximo 200 caracteres', max_length=200)),
                ('CedRepLegal', models.CharField(max_length=9)),
                ('NomRepLegal', models.TextField(help_text='Maximo 100 caracteres', max_length=100)),
                ('TelRepLegal', models.CharField(help_text='Maximo 12 caracteres', max_length=12)),
                ('telefono1', models.CharField(help_text='Maximo 12 caracteres', max_length=12)),
                ('telefono2', models.CharField(help_text='Maximo 12 caracteres', max_length=12)),
                ('correo', models.EmailField(help_text='Maximo 200 caracteres', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Cooperaivass',
            },
        ),
    ]
