# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_vehiculobaterias_vehiculos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculobaterias',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculobaterias',
            name='vehiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_items_baterias', to='principal.Vehiculos'),
        ),
    ]
