# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-31 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20170130_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoCauchos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('cauchos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_cauchos', to='principal.Cauchos')),
                ('vehiculos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_items_cauchos', to='principal.Vehiculos')),
            ],
            options={
                'verbose_name_plural': 'VehiculosCauchoss',
            },
        ),
    ]
