# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-02 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_vehiculocauchos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculobaterias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehiculocauchos',
            options={},
        ),
        migrations.AlterField(
            model_name='vehiculobaterias',
            name='baterias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Baterias'),
        ),
        migrations.AlterField(
            model_name='vehiculobaterias',
            name='vehiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Vehiculos'),
        ),
        migrations.AlterField(
            model_name='vehiculocauchos',
            name='cauchos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cauchos'),
        ),
        migrations.AlterField(
            model_name='vehiculocauchos',
            name='vehiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Vehiculos'),
        ),
    ]
