# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-28 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_auto_20170202_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculos',
            options={'verbose_name_plural': 'Vehiculos'},
        ),
    ]
