# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_auto_20170202_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoRines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('rines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Rines')),
            ],
        ),
        migrations.AlterModelOptions(
            name='vehiculos',
            options={'verbose_name_plural': 'Vehiculos'},
        ),
        migrations.AddField(
            model_name='vehiculorines',
            name='vehiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Vehiculos'),
        ),
    ]
