# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-05 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20170302_1459'),
        ('principal', '0015_auto_20170228_1047'),
    ]

    operations = [
    ]
